---

- src: calvinbui.ansible_pip
  version: '3.1.0'

- src: calvinbui.ansible_docker
  version: '2.0.0'

- src: calvinbui.ansible_git
  version: '1.1'

- src: calvinbui.ansible_nodejs
  version: '2.0.0'

- src: calvinbui.ansible_acme_certificates
  version: '1.6.0'

- src: calvinbui.ansible_awx
  version: '1.0'

- src: calvinbui.ansible_datadog
  version: '1.0.2'
